### ISSUE TITLE
Cannot see xUnit tests in Test Explorer

### ISSUE THREAD

**Issue by rroman81** [formulahendry/vscode-dotnet-test-explorer#109] opened 2018-08-03 20:45 UTC
I am having trouble with the extension's Test Explorer finding the xUnit tests under dotnet core 2.1.300 SDK.  The same project's tests are showing upunder VS2017 Enterprise, and I am able to execute them via "dotnet test" from the project folder.

Is there a way to increase the debug logs when extension attempts to do discovery?  

I can confirm that solution opens all the projects properly in the Omnisharp log, however the extension is unable to find the tests.

**Comment by stefanforsberg** [comment] 2018-08-04 08:00
Hmm, we do some logging in the output/test explorer terminal but for discovery it's not really that informative (basically only that it failed). Have you tried to set testProjectPath (if your test project is not in the workspace folder you need to do this)?

**Comment by SylChamber** [comment] 2018-08-08 18:55
Are you using display names in your tests?

```csharp
 [Fact(DisplayName = "DisplayName should be displayed")]
public void DisplayNameShouldBeDisplayed()
``` 

When I use the `DisplayName` property, the .NET Test Explorer can't discover tests.

**Comment by rroman81** [comment] 2018-08-09 21:40
@SylChamber No, I am not.  Just a standard ```[Fact]``` attribute that works in the VS IDE.

**Comment by MarcoNicolodi** [comment] 2018-08-15 11:30
My tests are discovered, but most of times the extension dont run them:

![screenshot from 2018-08-15 08-26-59](https://user-images.githubusercontent.com/8574010/44146233-1a5387ac-a065-11e8-9f79-d9d5a09d4764.png)

Also Xunit, standard [Fact] and 2.1.300

**Comment by stefanforsberg** [comment] 2018-08-15 11:46
@MarcoNicolodi Interesting. By "most of the time" do you mean it's seems to be random? Sometimes they are run and sometimes they are not?

**Comment by MarcoNicolodi** [comment] 2018-08-15 17:01
I just asked the whole team (~7devs) and they confirmed "Run All Tests" behavior stopped working. They said that they dont rely on the extension anymore because it became pretty unpredictable with our stack. I showed the them the image and they confirmed that its the default behavior for the extension nowadays. Most of times the "Run All Tests" button only run some tests, but never all. They said that the extension became more unpredictable over time and for that i wish i could send you more precise data.

Which kind of data would help the contributors to narrow down the problem?

**Comment by stefanforsberg** [comment] 2018-08-15 20:08
Hmm, I can think of one way to reproduce this error. Given your example above, let's say a developer open this workspace and test discovery generates the above tree. This would lead the extension to expect a test called Qualyteam.Storage.Tests.StorageControllerTests.Delete_ShoudCallService(etc). Now a developer changes the namespace Storage to MEGAStorage and run all tests. When xunit says that a test called Qualyteam.MEGAStorage.Tests.StorageControllerTests.Delete_ShoudCallService(etc) is passing or failed the tree view does not know how to handle that since it does not know that a test with that FQN exists. It seems maybe far fetched that those kind of rapid namespace changes would occur but it's the only thing I can think of at the top of my head.

It would be very interesting to hear if it's truly random, that is of you keep pressing Run all tests in the example above each test run results in different parts of the tree being not run. Would be really appreciated if you could give that a try.

**Comment by stefanforsberg** [comment] 2018-08-16 06:39
@rroman81 Latest version added some logging as to why discover failed. If you press the Show log icon (or go to Output/Test Explorer) you should see something like this:

> Executing dotnet test -t -v=q in (your dir name)
[ERROR] Error while executing dotnet test -t -v=q: (Reason for failing)

What do you see there?

**Comment by MarcoNicolodi** [comment] 2018-08-16 13:14
@stefanforsberg not random indeed. Pressing "Run All Tests" aways run the same tests:

![screenshot from 2018-08-16 10-12-35](https://user-images.githubusercontent.com/8574010/44210465-f2e4f100-a13c-11e8-95bb-1f0b52125d33.png)

Would you like any other info, like namespaces, etc?

**Comment by stefanforsberg** [comment] 2018-08-16 13:37
@MarcoNicolodi Yes, a full namespace with the class and test method(s) for test(s) not being picked up would be great. It looks like your method names are quite descriptive so maybe we run into something regarding char length.

**Comment by stefanforsberg** [comment] 2018-08-16 18:01
@MarcoNicolodi  After some experimenting I've learned that when a test name (FQN) is longer than 427 characters dotnet test upon discovery starts to abbreviate the test name with a "..."

![image](https://user-images.githubusercontent.com/358570/44225157-fd2edb80-a18c-11e8-87ce-64cbcdd2ccce.png)

This will explain why the tree does not mark the test result since it doesn't know the full name of the test.

Initially I thought this could be "fixed" by dropping down to dotnet vstest behavior but xunit [Theory]  does not seems to report itself in a expected format with that tool... because why on earth should the cli tools behave in a predictable and uniform way... think how boring that would make the world.

**Comment by MarcoNicolodi** [comment] 2018-08-17 11:30
Thanks for taking time to discover this. Im going to find a way to shorten either our method names or namespaces.

**Comment by MarcoNicolodi** [comment] 2018-08-17 12:18
@stefanforsber about the namespaces, we follow these guidelines:
For a project called `Qualyteam.Doc.Api.Web`, that has the `Qualyteam.Doc.Api.Web.Controllers`, `Qualyteam.Doc.Api.Web.Mappers` namespaces, we test it with a project called `Qualyteam.Doc.Api.Web.Tests`, and test the system under under with the `Qualyteam.Doc.Api.Web.Tests.Controllers`, `Qualyteam.Doc.Api.Web.Tests.Mappers` namespaces.

Its kind of confusing, and it might be confusing for the extension as well. It gets worse because we dont follow these rules all the times.

By the way, i just played with the extension a little, and noticed that tests that might have longer FQN are running while others that have shorter FQN are not:

![screenshot from 2018-08-17 09-00-04](https://user-images.githubusercontent.com/8574010/44265266-40746300-a1fc-11e8-92bc-d86ff3696dd0.png)


Another interesting fact:

When the `CategoryControllerTests` class has the `Qualyteam.Doc.Api.Web.Tests` namespace, i cant use the "right button + go to test" to go to the `Delete_IfServiceDoesntThrow_ShouldReturnOk` test. The extension notifies "Could not find test (namespace not matching uri)", although it finds the other test methods like `Update_IfCategoryIsNull_ShouldReturnBadRequest`.

But when i change the namespace to `Qualyteam.Doc.Api.Web.Tests.Controllers`, the extension can go to tests with no problem.

**Comment by stefanforsberg** [comment] 2018-08-17 13:51
@MarcoNicolodi Interesting, so then it's probably not related to the length of the test names then (I'll still write that discovery in the bonus column 🌮).

It would be great if you could open a terminal to your directory that the tests are executed from and write "dotnet test -t > tests.txt" (depending on your shell you might have to change the pipe char). Then execute all tests dotnet test --logger "trx;LogFileName=c:\temp\results.trx". Please attach both files (tests.txt and results.trx) here and maybe that can shed some light on the matter.

Regarding the "go to test" issues please open another issue for that one so it's easier to manage, thanks =)

**Comment by tdwright** [comment] 2018-08-20 23:04
Hi @stefanforsberg, I'm also having an issue where my (XUnit) tests don't show up in the explorer.

Looking at the output, it seems to be looking at every project in my workspace for tests. It does appear to find tests in my test project (the output screen shows them all listed), but they don't show up in the explorer pane.

For completeness, when I nav to the test project and run `dotnet test` the tests all pass.

Any idea what's going on here?

**Comment by tdwright** [comment] 2018-08-21 02:10
Quick update... Either the act of updating VS Code or simply restarting it seems to have solved the issue. Is the test project path setting only read at startup?

**Comment by MarcoNicolodi** [comment] 2018-08-21 11:53
@stefanforsberg if a log to a single file each test overwrites the whole file, therefore at the end id have the results of the last test only. Is there any way to make the results.trx keep the results of all tests, or should i attach here all the logs in separated files?

**Comment by stefanforsberg** [comment] 2018-08-21 12:03
@tdwright Right, it does require a restart.  Could you please file a separate issue on that and we'll get it fixed.

@MarcoNicolodi Ah, you have multiple test project then I suppose? Then all the files would be helpful =)

**Comment by tdwright** [comment] 2018-08-21 12:09
@stefanforsberg Your wish, sir, is my command... #119

**Comment by MarcoNicolodi** [comment] 2018-08-21 13:00
Here are the files you asked for :)

[results.zip](https://github.com/formulahendry/vscode-dotnet-test-explorer/files/2306332/results.zip)

**Comment by stefanforsberg** [comment] 2018-08-21 14:16
@MarcoNicolodi Hmm, everything looks like it should.

1:
If you open the folder containing the testproject resulting in Qualyteam.Doc.Api.Web.Tests.dll, how does that extension work then? Cause by the looks of the above image the tree view results pick up the tests for the AdminControllerTests but not for the CategoryControllerTests.

2:
Also regarding what you said earlier about the extension becoming more unreliable over time, the support for multiple test projects only came like 10 days ago, where you running it one test project at a time previously?

**Comment by MarcoNicolodi** [comment] 2018-08-22 12:35
@stefanforsberg  theres a little bit of randomness i think. Take a look at my tree view now:

![screenshot from 2018-08-22 09-17-15](https://user-images.githubusercontent.com/8574010/44462855-439c9400-a5ec-11e8-9d3d-b9b5c7a6af63.png)

I just asked my team and they said that the behavior is pretty random. They use the extension mostly to run specific tests, but seldom run all tests, since it doesnt work, and they are not pretty sure it has ever worked for our tests (multi projects). 

And even though some tests have the question mark, if i run them separatedly, the extesion run it and show the results. For example: 
 
![screenshot from 2018-08-22 09-29-13](https://user-images.githubusercontent.com/8574010/44463439-17821280-a5ee-11e8-92a2-9d2888325ea1.png)

This test is discovered and flagged with this question mark. When i run all, either the extension doesnt run it or at least doesnt mark it as. But if i run this test separatedly, the extension runs it and marks as passed/failed as it should. 


2: We are using multiple test projects since forever, but as I said, we are not sure it has ever worked.

**Comment by stefanforsberg** [comment] 2018-08-22 13:11
@MarcoNicolodi Ah great, thanks for helping me troubleshoot this!

**Comment by stefanforsberg** [comment] 2018-08-27 10:00
I'm going to close this @rroman81. If you still are having problems please open a new issue.

**Closed by stefanforsberg** 2018-08-27 10:00 UTC
Labels: need more info

**Comment by Meligy** [comment] 2019-01-30 23:08
Funny enough I came here because in an earlier version of the extension I set `testProjectPath` to `**/*.csporj` to allow discovery to go multiple folder levels. Then in a new project I cloned recently it was unable to discover anything - while `dotnet test` worked just fine.

I totally forgot that the pattern was a custom one, until I saw this thread, and removed the pattern, then discovery just worked!
