### ISSUE TITLE
CodeLens test statuses not showing in tests

### ISSUE THREAD

**Issue by NimbleHive** [formulahendry/vscode-dotnet-test-explorer#172] opened 2018-12-29 13:05 UTC
### Environment Data
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
### Steps to reproduce
Created test project with couple of sample tests.  Tests pass in the .Net Test Explorer but are not showing in Code Lens.  See screenshot:

![image](https://user-images.githubusercontent.com/22554759/50538615-0d88a580-0bc6-11e9-9535-cc32ffdce5fc.png)

### Expected behaviour
CodeLens showing tick or pass/fail
###Actual Behaviour
Nothing

###Notes
I have tried changing dotnet-test-explorer.pathForResultFile as per https://github.com/formulahendry/vscode-dotnet-test-explorer/issues/33

I don't know if the file is immediately deleted from the path when created, but I never see d:\Temp\test-explorer\0.trx.  When I run the command line manually it creates it and keeps it there though:
dotnet test --no-build --logger "trx;LogFileName=d:\Temp\test-explorer\0.trx"

**Comment by stefanforsberg** [comment] 2019-01-03 13:42
Hello! As you say the file is deleted as soon as we've parsed it (since the tree shows the green check marks that part works).  Kind of hard to tell from the screenshot what fails, would it be possible to create a test file that reproduces the error?

**Comment by NimbleHive** [comment] 2019-01-06 01:37
Sure, what would you want test file to be?

**Comment by stefanforsberg** [comment] 2019-01-06 15:54
A file (or just some code) that reproduces the error on your machine.

**Comment by lcrsantos** [comment] 2019-01-07 12:43
I can reproduce this in this simple repository

https://github.com/lcrsantos/codelensnetcoreexplorer

Also cannot run live testing.. maybe those could be related.

**Comment by stefanforsberg** [comment] 2019-01-07 19:49
Thanks for the repo, I'll take a look.

And just to clarify, when you say "live testing", what do you mean by that?

**Comment by lcrsantos** [comment] 2019-01-07 23:10
Whenever the code that the test affetcs or the code of the test itself
changes the test automatically reexecutes.. i think there's a setting for
that. Something like watch functionality..

Na(o) segunda, 7 de jan de 2019, 19:49, Stefan Forsberg <
notifications@github.com> escreveu:

**Comment by lcrsantos** [comment] 2019-01-15 16:52
Any updates on this? I've managed to put watch working defining the glob for test path but codelens integration is still not available

**Comment by stefanforsberg** [comment] 2019-01-19 19:16
I'm afraid I've got to use the old "works on my machine" answer here, I can not reproduce the code lens issue with the linked repo I'm afraid.

![image](https://user-images.githubusercontent.com/358570/51431287-11d53b00-1c27-11e9-811d-0973589f9ab6.png)

**Comment by dawoodmm** [comment] 2019-01-30 22:45
@stefanforsberg 

Having the same issue
![image](https://user-images.githubusercontent.com/3035718/52017846-3692a380-24ae-11e9-84ab-a2a9fe78a4e4.png)

also got this error in the Test Explorer terminal
```
PS C:\SandBox\codelensnetcoreexplorer-master> dotnet watch test --logger "trx;LogFileName=C:\temp\test-explorer-W8734g\autoWatch.trx"\
watch : Could not find a MSBuild project file in 'C:\SandBox\codelensnetcoreexplorer-master'. Specify which project to use with the --project option.

```

**Comment by bmccord** [comment] 2019-02-20 16:20
I'm having the same problem as listed here. I have tried changing the pathForResultFile, but that hasn't helped. I have disabled all extensions except for .NET Test Explorer and C#. That hasn't helped. I have tried to find the .trx file, but it doesn't look like it is being produced. My console output looks like this:

Executing dotnet build in /Users/bmccord2/Projects/cobwow-api/WOWApi.Tests
Executing dotnet test --no-build --logger "trx;LogFileName=/Users/bmccord2/Projects/cobwow-api/TestResults/test-explorer/0.trx" in /Users/bmccord2/Projects/cobwow-api/WOWApi.Tests
Process 17815 started
Test run for /Users/bmccord2/Projects/cobwow-api/WOWApi.Tests/bin/Debug/netcoreapp2.2/Optum.PaymentIntegrity.WOWApi.Tests.dll(.NETCoreApp,Version=v2.2)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation. All rights reserved.

Starting test execution, please wait...
Results File: /Users/bmccord2/Projects/cobwow-api/TestResults/test-explorer/0.trx

Total tests: 257. Passed: 257. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 17.0079 Seconds

Process 17815 finished

When I go to /Users/bmccord2/Projects/cobwow-api/TestResults/test-explorerer, there is no file there. I'm on a Mac.

Any ideas?

**Comment by stefanforsberg** [comment] 2019-02-20 17:45
Hello! We have just pushed a fix for codelens that was primarily for users of xunit. The fix is not live yet but will hopefully be released soon.

Regarding the trx file that file is deleted after we've parsed it to not clutter your hd with files.

**Comment by stefanforsberg** [comment] 2019-02-23 13:55
Hello, 0.6.3 was released and I'm curious if that has made codelens displaying work better?

**Comment by bmccord** [comment] 2019-02-26 15:00
The icon is now showing in CodeLens, see picture:

![screen shot 2019-02-26 at 8 58 29 am](https://user-images.githubusercontent.com/1359220/53422241-baa05400-39a4-11e9-9de0-cbcb8b9adadb.png)

One question I have is this.  It seems to update / show the icon when running the tests from the Explorer window, but not when running them from the codelens links.  Is that normal?

**Comment by stefanforsberg** [comment] 2019-02-26 16:21
Great, thanks for reporting!

The code lens run test/debug test are added by the c# plugin itself and currently our extension can not react when tests are run that way.

**Closed by stefanforsberg** 2019-02-26 16:21 UTC

**Comment by NimbleHive** [comment] 2019-02-26 18:09
I confirm working for me now - thanks!

One question - in your example the tick is shown next to "Run Test | Debug Test", how do you turn this on:
![image](https://user-images.githubusercontent.com/22554759/53435841-df043b00-3a4d-11e9-9e37-a8fa06c1df12.png)

**Comment by stefanforsberg** [comment] 2019-03-01 19:56
@NimbleHive Hmm, I think that screenshot is from an older version. The placement of our symbols now seems to be above the attribute as indicated by the screenshot from @bmccord just above. We don't really control exactly where the symbol ends up, we just tell the code lens provider that the symbol should be displayed.

I'm also considering dropping the code lens display and adding gutter display instead. That would place the symbol near the same place were you add break points. Thoughts on that?

**Comment by NimbleHive** [comment] 2019-03-05 18:32
I did wonder if that was the case.  Either way is good - Gutter would take up slightly less room though. The tick next to the Run Test|Debug Test is most useful, but understand that you don't have control of it.
